# -*- coding: utf-8 -*-

import os
import textwrap

from nose.tools import *

from wp2mt.converter import convert


def test_execute_01():
    """
    execute()：WordPress形式のファイルをMovableType形式に変換することを確認する。
    """
    expected = textwrap.dedent("""\
        AUTHOR: 7pairs
        TITLE: 1つ目の記事
        STATUS: publish
        ALLOW COMMENTS: 0
        CONVERT BREAKS: __default__
        ALLOW PINGS: 0
        PRIMARY CATEGORY: はてなダイアリー過去ログ
        CATEGORY: はてなダイアリー過去ログ

        DATE: 07/14/2004 12:00:00 AM
        -----
        BODY:
        1つ目の記事1行目
        1つ目の記事2行目
        1つ目の記事3行目

        -----
        EXTENDED BODY:

        -----
        EXCERPT:

        -----
        KEYWORDS:

        -----


        --------
        AUTHOR: 7pairs
        TITLE: 2つ目の記事
        STATUS: publish
        ALLOW COMMENTS: 0
        CONVERT BREAKS: __default__
        ALLOW PINGS: 0
        PRIMARY CATEGORY: はてなダイアリー過去ログ
        CATEGORY: はてなダイアリー過去ログ

        DATE: 07/15/2004 12:00:00 AM
        -----
        BODY:
        2つ目の記事1行目
        2つ目の記事2行目
        2つ目の記事3行目

        -----
        EXTENDED BODY:

        -----
        EXCERPT:

        -----
        KEYWORDS:

        -----


        --------
    """)
    convert.execute('./wp2mt/tests/in/test_execute_01.xml', './wp2mt/tests/out/test_execute_01.txt')

    with open('./wp2mt/tests/out/test_execute_01.txt') as f:
        result = f.read()
    assert_equal(expected, result)

    os.remove('./wp2mt/tests/out/test_execute_01.txt')


def test_read_file_01():
    """
    read_file()：引数に有効なファイルパスを指定したとき、そのファイルの内容を文字列として返すことを確認する。
    """
    result = convert.read_file('./wp2mt/tests/in/test_read_file_01.xml')
    assert_equal('<test>ファイル読み込みのテスト</test>', result)


def test_read_file_02():
    """
    read_file()：引数に無効なファイルパスを指定したとき、空文字列を返すことを確認する。
    """
    result = convert.read_file('./wp2mt/tests/in/not_exists.xml')
    assert_equal('', result)


def test_parse_xml_01():
    """
    parse_xml()：引数に有効なXML文字列を指定したとき、その内容を辞書として返すことを確認する。
    """
    expected = {
        'author': '7pairs',
        'title': '1つ目の記事',
        'category': 'はてなダイアリー過去ログ',
        'date': '07/14/2004 12:00:00 AM',
        'body': textwrap.dedent("""\
            1つ目の記事1行目
            1つ目の記事2行目
            1つ目の記事3行目
        """),
    }
    result = next(convert.parse_xml(textwrap.dedent("""\
        <?xml version="1.0" encoding="UTF-8" ?>
        <!-- This is a WordPress eXtended RSS file generated by WordPress as an export of your site. -->
        <!-- It contains information about your site's posts, pages, comments, categories, and other content. -->
        <!-- You may use this file to transfer that content from one site to another. -->
        <!-- This file is not intended to serve as a complete backup of your site. -->

        <!-- To import this information into a WordPress site follow these steps: -->
        <!-- 1. Log in to that site as an administrator. -->
        <!-- 2. Go to Tools: Import in the WordPress admin panel. -->
        <!-- 3. Install the "WordPress" importer from the list. -->
        <!-- 4. Activate & Run Importer. -->
        <!-- 5. Upload this file using the form provided on that page. -->
        <!-- 6. You will first be asked to map the authors in this export file to users -->
        <!--    on the site. For each author, you may choose to map to an -->
        <!--    existing user on the site or to create a new user. -->
        <!-- 7. WordPress will then import each of the posts, pages, comments, categories, etc. -->
        <!--    contained in this file into your site. -->

        <!-- generator="WordPress/3.5.1" created="2014-05-05 04:25" -->
        <rss version="2.0"
            xmlns:excerpt="http://wordpress.org/export/1.2/excerpt/"
            xmlns:content="http://purl.org/rss/1.0/modules/content/"
            xmlns:wfw="http://wellformedweb.org/CommentAPI/"
            xmlns:dc="http://purl.org/dc/elements/1.1/"
            xmlns:wp="http://wordpress.org/export/1.2/"
        >

            <channel>
                <title>しょーとさーきっと。</title>
                <link>http://short-circuit.jp</link>
                <description></description>
                <pubDate>Mon, 05 May 2014 04:25:56 +0000</pubDate>
                <language>ja</language>
                <wp:wxr_version>1.2</wp:wxr_version>
                <wp:base_site_url>http://short-circuit.jp</wp:base_site_url>
                <wp:base_blog_url>http://short-circuit.jp</wp:base_blog_url>

                <wp:author><wp:author_id>1</wp:author_id><wp:author_login>7pairs</wp:author_login><wp:author_email>7pairs@gmail.com</wp:author_email><wp:author_display_name><![CDATA[ちぃといつ]]></wp:author_display_name><wp:author_first_name><![CDATA[]]></wp:author_first_name><wp:author_last_name><![CDATA[]]></wp:author_last_name></wp:author>

                <generator>http://wordpress.org/?v=3.5.1</generator>

                <item>
                    <title>1つ目の記事</title>
                    <link>http://short-circuit.jp/2004/07/14/000000</link>
                    <pubDate>Tue, 13 Jul 2004 15:00:00 +0000</pubDate>
                    <dc:creator>7pairs</dc:creator>
                    <guid isPermaLink="false">http://short-circuit.jp/unclassified/20040714000000</guid>
                    <description></description>
                    <content:encoded><![CDATA[1つ目の記事1行目
        1つ目の記事2行目
        1つ目の記事3行目
        ]]></content:encoded>
                    <excerpt:encoded><![CDATA[]]></excerpt:encoded>
                    <wp:post_id>6</wp:post_id>
                    <wp:post_date>2004-07-14 00:00:00</wp:post_date>
                    <wp:post_date_gmt>2004-07-13 15:00:00</wp:post_date_gmt>
                    <wp:comment_status>open</wp:comment_status>
                    <wp:ping_status>open</wp:ping_status>
                    <wp:post_name>2004-07-14-wed</wp:post_name>
                    <wp:status>publish</wp:status>
                    <wp:post_parent>0</wp:post_parent>
                    <wp:menu_order>0</wp:menu_order>
                    <wp:post_type>post</wp:post_type>
                    <wp:post_password></wp:post_password>
                    <wp:is_sticky>0</wp:is_sticky>
                    <category domain="category" nicename="hatena-diary"><![CDATA[はてなダイアリー過去ログ]]></category>
                    <wp:postmeta>
                        <wp:meta_key>_edit_last</wp:meta_key>
                        <wp:meta_value><![CDATA[1]]></wp:meta_value>
                    </wp:postmeta>
                    <wp:postmeta>
                        <wp:meta_key>has_been_twittered</wp:meta_key>
                        <wp:meta_value><![CDATA[failed]]></wp:meta_value>
                    </wp:postmeta>
                    <wp:postmeta>
                        <wp:meta_key>twitter_failure_code</wp:meta_key>
                        <wp:meta_value><![CDATA[400]]></wp:meta_value>
                    </wp:postmeta>
                    <wp:postmeta>
                        <wp:meta_key>twitter_failure_reason</wp:meta_key>
                        <wp:meta_value><![CDATA[Settings do not permit the auto-tweeting of old posts]]></wp:meta_value>
                    </wp:postmeta>
                </item>
            </channel>
        </rss>
    """)))
    assert_equal(expected, result)


def test_create_mt_data_01():
    """
    create_mt_data()：引数に辞書を指定したとき、MovableType形式の文字列を返すことを確認する。
    """
    data = {
        'author': '7pairs',
        'title': '1つ目の記事',
        'category': 'はてなダイアリー過去ログ',
        'date': '07/14/2004 12:00:00 AM',
        'body': textwrap.dedent("""\
            1つ目の記事1行目
            1つ目の記事2行目
            1つ目の記事3行目
        """),
    }
    expected = textwrap.dedent("""\
        AUTHOR: 7pairs
        TITLE: 1つ目の記事
        STATUS: publish
        ALLOW COMMENTS: 0
        CONVERT BREAKS: __default__
        ALLOW PINGS: 0
        PRIMARY CATEGORY: はてなダイアリー過去ログ
        CATEGORY: はてなダイアリー過去ログ

        DATE: 07/14/2004 12:00:00 AM
        -----
        BODY:
        1つ目の記事1行目
        1つ目の記事2行目
        1つ目の記事3行目

        -----
        EXTENDED BODY:

        -----
        EXCERPT:

        -----
        KEYWORDS:

        -----


        --------
    """)
    result = convert.create_mt_data(data)
    assert_equal(expected, result)


def test_save_file_01():
    """
    save_file()：引数に文字列とファイル名を指定したとき、文字列の内容をファイルに保存することを確認する。
    """
    data = textwrap.dedent("""\
        保存する文字列アルよー。
        これは2行目アルよー。
    """)
    convert.save_file('./wp2mt/tests/out/test_save_file_01.txt', data)

    with open('./wp2mt/tests/out/test_save_file_01.txt') as f:
        result = f.read()
    assert_equal(data, result)

    os.remove('./wp2mt/tests/out/test_save_file_01.txt')
